# Generated by Django 4.2 on 2026-03-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('target_time', models.DateTimeField()),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('min_price_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_price_30d', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arima_prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lstm_prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cnn_prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('arima_error', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lstm_error', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cnn_error', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
