# Generated by Django 6.0.3 on 2026-03-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_sentimentmodels'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sentimentarticle',
            new_name='stocks_sent_ticker_69b5d3_idx',
            old_name='sentiment_ticker_fetched_idx',
        ),
        migrations.RenameIndex(
            model_name='sentimentarticle',
            new_name='stocks_sent_sector_c6db3a_idx',
            old_name='sentiment_sector_fetched_idx',
        ),
    ]
