# Generated by Django 6.0.3 on 2026-03-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_sentiment_ticker_fetched_idx_stocks_sent_ticker_69b5d3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
