# Generated by Django 6.0.3 on 2026-03-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_usersecurityprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
