# Generated by Django 6.0.3 on 2026-03-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_usersecurityprofile_security_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_fetching',
            field=models.BooleanField(default=False, help_text='Lock to prevent concurrent news fetches'),
        ),
    ]
