# Generated by Django 6.0.3 on 2026-03-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_stock_is_fetching'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersecurityprofile',
            name='last_otp_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='otp_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='usersecurityprofile',
            name='reset_token_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
